name: Sync CSV to S3

on:
  push:
    branches:
      - main  # Trigger when a CSV file is pushed to the 'main' branch
    paths:
      - '**/*.csv'  # Only trigger when a CSV file is changed
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  sync-to-s3:
    runs-on: ubuntu-latest  # The action will run on an Ubuntu runner
    
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2  # This step checks out the repository code

      - name: Set up AWS CLI (Pre-installed)
        run: |
          aws --version  # Check if AWS CLI is already installed and display the version
          
      - name: Upload CSV files to S3
        run: |
          for file in ./*.csv; do
            aws s3 cp "$file" s3://my-github-csv-files/  # Upload each CSV file individually to the correct bucket
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secret for Access Key
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secret for Secret Access Key
          AWS_DEFAULT_REGION: "ap-southeast-1"  # Correct region for Australia (Melbourne)
