name: Sync CSV to S3

on:
  push:
    branches:
      - main
    paths:
      - '**/*.csv'
  workflow_dispatch:  # This allows you to manually trigger the workflow from GitHub


jobs:
  sync-to-s3:
    runs-on: ubuntu-latest  # The action will run on an Ubuntu runner
    
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2  # This step checks out the repository code

      - name: Set up AWS CLI (Alternative Method)
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install  # Alternative install method

      - name: Upload CSV to S3
        run: |
          aws s3 cp ./path-to-your-csv/*.csv s3://your-bucket-name/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # GitHub Secret for Access Key
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # GitHub Secret for Secret Access Key
          AWS_DEFAULT_REGION: "us-east-1"  # Optional: Update to your AWS region
